# Generated by Django 3.1.6 on 2021-05-08 20:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Essential', 'Essential'), ('Sanitization', 'Sanitization')], max_length=50, null=True)),
                ('supplier', models.CharField(max_length=50, null=True)),
                ('supplier_contact', phone_field.models.PhoneField(max_length=31, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
