# Generated by Django 3.1.6 on 2021-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_crm', '0002_auto_20210509_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Patient_Type',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient')], default='Inpatient', max_length=10),
        ),
        migrations.DeleteModel(
            name='Patient_Type',
        ),
    ]
