# Generated by Django 3.1.6 on 2021-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_crm', '0007_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='Comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
